DEFINT A-Z
DECLARE SUB Center (row, text$)
10 CLS
   SCREEN 9
   PALETTE 0, 7
   COLOR 9
   Center 6, "Apresenta"
   Center 5, "FJAS"
   COLOR 2
   FOR T = 52 TO 599 STEP 2
   A = 40
   PSET (T, A)
   NEXT T
   FOR T = 52 TO 599 STEP 2
   A = 41
   PSET (T, A)
   NEXT T
   FOR T = 52 TO 599 STEP 2
   A = 42
   PSET (T, A)
   NEXT T
   FOR T = 52 TO 599 STEP 2
   A = 43
   PSET (T, A)
   NEXT T
   FOR T = 52 TO 599 STEP 2
   A = 44
   PSET (T, A)
   NEXT T
   FOR T = 52 TO 599 STEP 2
   A = 45
   PSET (T, A)
   NEXT T
   FOR T = 52 TO 599 STEP 2
   A = 46
   PSET (T, A)
   NEXT T
   FOR T = 52 TO 599 STEP 2
   A = 47
   PSET (T, A)
   NEXT T
   FOR T = 52 TO 599 STEP 2
   A = 48
   PSET (T, A)
   NEXT T
   FOR T = 52 TO 599 STEP 2
   A = 49
   PSET (T, A)
   NEXT T
   FOR T = 52 TO 599 STEP 2
   A = 50
   PSET (T, A)
   NEXT T
   FOR T = 52 TO 599 STEP 2
   A = 51
   PSET (T, A)
   NEXT T
   FOR T = 52 TO 599 STEP 2
   A = 52
   PSET (T, A)
   NEXT T
   FOR T = 52 TO 599 STEP 2
   A = 53
   PSET (T, A)
   NEXT T
   FOR T = 52 TO 599 STEP 2
   A = 54
   PSET (T, A)
   NEXT T
   FOR T = 52 TO 599 STEP 2
   A = 55
   PSET (T, A)
   NEXT T
   FOR T = 52 TO 599 STEP 2
   A = 56
   PSET (T, A)
   NEXT T
   FOR T = 52 TO 599 STEP 2
   A = 57
   PSET (T, A)
   NEXT T
   FOR T = 52 TO 599 STEP 2
   A = 58
   PSET (T, A)
   NEXT T
   FOR T = 52 TO 599 STEP 2
   A = 59
   PSET (T, A)
   NEXT T
   FOR T = 52 TO 599 STEP 2
   A = 60
   PSET (T, A)
   NEXT T
   FOR T = 52 TO 599 STEP 2
   A = 61
   PSET (T, A)
   NEXT T
   FOR T = 52 TO 599 STEP 2
   A = 62
   PSET (T, A)
   NEXT T
   FOR T = 52 TO 599 STEP 2
   A = 63
   PSET (T, A)
   NEXT T
   FOR T = 52 TO 599 STEP 2
   A = 64
   PSET (T, A)
   NEXT T
   FOR T = 52 TO 599 STEP 2
   A = 65
   PSET (T, A)
   NEXT T
   FOR T = 52 TO 599 STEP 2
   A = 66
   PSET (T, A)
   NEXT T
   FOR T = 52 TO 599 STEP 2
   A = 67
   PSET (T, A)
   NEXT T
   FOR T = 52 TO 599 STEP 2
   A = 68
   PSET (T, A)
   NEXT T
   FOR T = 52 TO 599 STEP 2
   A = 69
   PSET (T, A)
   NEXT T
   FOR T = 52 TO 599 STEP 2
   A = 70
   PSET (T, A)
   NEXT T
   FOR T = 52 TO 599 STEP 2
   A = 71
   PSET (T, A)
   NEXT T
   FOR T = 52 TO 599 STEP 2
   A = 72
   PSET (T, A)
   NEXT T
   FOR T = 52 TO 599 STEP 2
   A = 73
   PSET (T, A)
   NEXT T
   FOR T = 52 TO 599 STEP 2
   A = 74
   PSET (T, A)
   NEXT T
   FOR T = 52 TO 599 STEP 2
   A = 75
   PSET (T, A)
   NEXT T
   FOR T = 52 TO 599 STEP 2
   A = 76
   PSET (T, A)
   NEXT T
   FOR T = 52 TO 599 STEP 2
   A = 77
   PSET (T, A)
   NEXT T
   FOR T = 52 TO 599 STEP 2
   A = 78
   PSET (T, A)
   NEXT T
   FOR T = 52 TO 599 STEP 2
   A = 79
   PSET (T, A)
   NEXT T
   FOR T = 52 TO 599 STEP 2
   A = 80
   PSET (T, A)
   NEXT T
   FOR T = 52 TO 599 STEP 2
   A = 81
   PSET (T, A)
   NEXT T
   FOR T = 52 TO 599 STEP 2
   A = 82
   PSET (T, A)
   NEXT T
   FOR T = 52 TO 599 STEP 2
   A = 83
   PSET (T, A)
   NEXT T
   FOR T = 52 TO 599 STEP 2
   A = 84
   PSET (T, A)
   NEXT T
   FOR T = 52 TO 599 STEP 2
   A = 85
   PSET (T, A)
   NEXT T
   FOR T = 52 TO 599 STEP 2
   A = 86
   PSET (T, A)
   NEXT T
   FOR T = 52 TO 599 STEP 2
   A = 87
   PSET (T, A)
   NEXT T
   FOR T = 52 TO 599 STEP 2
   A = 88
   PSET (T, A)
   NEXT T
   FOR T = 52 TO 599 STEP 2
   A = 89
   PSET (T, A)
   NEXT T
   FOR T = 52 TO 599 STEP 2
   A = 90
   PSET (T, A)
   NEXT T
   FOR T = 52 TO 599 STEP 2
   A = 91
   PSET (T, A)
   NEXT T
   FOR T = 52 TO 599 STEP 2
   A = 92
   PSET (T, A)
   NEXT T
   FOR T = 52 TO 599 STEP 2
   A = 93
   PSET (T, A)
   NEXT T
   FOR T = 52 TO 599 STEP 2
   A = 94
   PSET (T, A)
   NEXT T
   FOR T = 52 TO 599 STEP 2
   A = 95
   PSET (T, A)
   NEXT T
   FOR T = 52 TO 599 STEP 2
   A = 96
   PSET (T, A)
   NEXT T
   FOR T = 52 TO 599 STEP 2
   A = 97
   PSET (T, A)
   NEXT T
   FOR T = 52 TO 599 STEP 2
   A = 98
   PSET (T, A)
   NEXT T
   FOR T = 52 TO 599 STEP 2
   A = 99
   PSET (T, A)
   NEXT T
  
   COLOR
   FOR T = 52 TO 599 STEP 1
   A = 100
   PSET (T, A)
   NEXT T
   FOR T = 52 TO 599 STEP 1
   A = 101
   PSET (T, A)
   NEXT T
   FOR T = 52 TO 599 STEP 1
   A = 102
   PSET (T, A)
   NEXT T
   FOR T = 52 TO 599 STEP 1
   A = 103
   PSET (T, A)
   NEXT T
   FOR T = 52 TO 599 STEP 1
   A = 104
   PSET (T, A)
   NEXT T
   FOR T = 52 TO 599 STEP 1
   A = 105
   PSET (T, A)
   NEXT T
   FOR T = 52 TO 599 STEP 1
   A = 106
   PSET (T, A)
   NEXT T
   FOR T = 52 TO 599 STEP 1
   A = 107
   PSET (T, A)
   NEXT T
   FOR T = 52 TO 599 STEP 1
   A = 108
   PSET (T, A)
   NEXT T
   FOR T = 52 TO 599 STEP 1
   A = 109
   PSET (T, A)
   NEXT T
   FOR T = 52 TO 599 STEP 1
   A = 110
   PSET (T, A)
   NEXT T
   FOR T = 52 TO 599 STEP 1
   A = 111
   PSET (T, A)
   NEXT T
   FOR T = 52 TO 599 STEP 1
   A = 112
   PSET (T, A)
   NEXT T
   FOR T = 52 TO 599 STEP 1
   A = 113
   PSET (T, A)
   NEXT T
   FOR T = 52 TO 599 STEP 1
   A = 114
   PSET (T, A)
   NEXT T
   FOR T = 52 TO 599 STEP 1
   A = 115
   PSET (T, A)
   NEXT T
   FOR T = 52 TO 599 STEP 1
   A = 116
   PSET (T, A)
   NEXT T
   FOR T = 52 TO 599 STEP 1
   A = 117
   PSET (T, A)
   NEXT T
   FOR T = 52 TO 599 STEP 1
   A = 118
   PSET (T, A)
   NEXT T
   FOR T = 52 TO 599 STEP 1
   A = 119
   PSET (T, A)
   NEXT T
   FOR T = 52 TO 599 STEP 1
   A = 120
   PSET (T, A)
   NEXT T
   FOR T = 52 TO 599 STEP 1
   A = 121
   PSET (T, A)
   NEXT T
   FOR T = 52 TO 599 STEP 1
   A = 122
   PSET (T, A)
   NEXT T
   FOR T = 52 TO 599 STEP 1
   A = 123
   PSET (T, A)
   NEXT T
   FOR T = 52 TO 599 STEP 1
   A = 124
   PSET (T, A)
   NEXT T
   FOR T = 52 TO 599 STEP 1
   A = 125
   PSET (T, A)
   NEXT T
   FOR T = 52 TO 599 STEP 1
   A = 126
   PSET (T, A)
   NEXT T
   FOR T = 52 TO 599 STEP 1
   A = 127
   PSET (T, A)
   NEXT T
   FOR T = 52 TO 599 STEP 1
   A = 128
   PSET (T, A)
   NEXT T
   FOR T = 52 TO 599 STEP 1
   A = 129
   PSET (T, A)
   NEXT T
   FOR T = 52 TO 599 STEP 1
   A = 130
   PSET (T, A)
   NEXT T
   FOR T = 52 TO 599 STEP 1
   A = 131
   PSET (T, A)
   NEXT T
   FOR T = 52 TO 599 STEP 1
   A = 132
   PSET (T, A)
   NEXT T
   FOR T = 52 TO 599 STEP 1
   A = 133
   PSET (T, A)
   NEXT T
   FOR T = 52 TO 599 STEP 1
   A = 134
   PSET (T, A)
   NEXT T
   FOR T = 52 TO 599 STEP 1
   A = 135
   PSET (T, A)
   NEXT T
   FOR T = 52 TO 599 STEP 1
   A = 136
   PSET (T, A)
   NEXT T
   FOR T = 52 TO 599 STEP 1
   A = 137
   PSET (T, A)
   NEXT T
   FOR T = 52 TO 599 STEP 1
   A = 138
   PSET (T, A)
   NEXT T
   FOR T = 52 TO 599 STEP 1
   A = 139
   PSET (T, A)
   NEXT T
   FOR T = 52 TO 599 STEP 1
   A = 140
   PSET (T, A)
   NEXT T
   FOR T = 52 TO 599 STEP 1
   A = 141
   PSET (T, A)
   NEXT T
   FOR T = 52 TO 599 STEP 1
   A = 142
   PSET (T, A)
   NEXT T
   FOR T = 52 TO 599 STEP 1
   A = 143
   PSET (T, A)
   NEXT T
   FOR T = 52 TO 599 STEP 1
   A = 144
   PSET (T, A)
   NEXT T
   FOR T = 52 TO 599 STEP 1
   A = 145
   PSET (T, A)
   NEXT T
   FOR T = 52 TO 599 STEP 1
   A = 146
   PSET (T, A)
   NEXT T
   FOR T = 52 TO 599 STEP 1
   A = 147
   PSET (T, A)
   NEXT T
   FOR T = 52 TO 599 STEP 1
   A = 148
   PSET (T, A)
   NEXT T
   FOR T = 52 TO 599 STEP 1
   A = 149
   PSET (T, A)
   NEXT T
   FOR T = 52 TO 599 STEP 1
   A = 150
   PSET (T, A)
   NEXT T
   FOR T = 52 TO 599 STEP 1
   A = 151
   PSET (T, A)
   NEXT T
   FOR T = 52 TO 599 STEP 1
   A = 152
   PSET (T, A)
   NEXT T
   FOR T = 52 TO 599 STEP 1
   A = 153
   PSET (T, A)
   NEXT T
   FOR T = 52 TO 599 STEP 1
   A = 154
   PSET (T, A)
   NEXT T
   FOR T = 52 TO 599 STEP 1
   A = 155
   PSET (T, A)
   NEXT T
   FOR T = 52 TO 599 STEP 1
   A = 156
   PSET (T, A)
   NEXT T
   FOR T = 52 TO 599 STEP 1
   A = 157
   PSET (T, A)
   NEXT T
   FOR T = 52 TO 599 STEP 1
   A = 158
   PSET (T, A)
   NEXT T
   FOR T = 52 TO 599 STEP 1
   A = 159
   PSET (T, A)
   NEXT T
   FOR T = 52 TO 599 STEP 1
   A = 160
   PSET (T, A)
   NEXT T
   FOR T = 52 TO 599 STEP 1
   A = 161
   PSET (T, A)
   NEXT T
   FOR T = 52 TO 599 STEP 1
   A = 162
   PSET (T, A)
   NEXT T
   FOR T = 52 TO 599 STEP 1
   A = 163
   PSET (T, A)
   NEXT T
   FOR T = 52 TO 599 STEP 1
   A = 164
   PSET (T, A)
   NEXT T
   FOR T = 52 TO 599 STEP 1
   A = 165
   PSET (T, A)
   NEXT T
   FOR T = 52 TO 599 STEP 1
   A = 166
   PSET (T, A)
   NEXT T
   FOR T = 52 TO 599 STEP 1
   A = 167
   PSET (T, A)
   NEXT T
   FOR T = 52 TO 599 STEP 1
   A = 168
   PSET (T, A)
   NEXT T
   FOR T = 52 TO 599 STEP 1
   A = 169
   PSET (T, A)
   NEXT T
   FOR T = 52 TO 599 STEP 1
   A = 170
   PSET (T, A)
   NEXT T
   FOR T = 52 TO 599 STEP 1
   A = 171
   PSET (T, A)
   NEXT T
   FOR T = 52 TO 599 STEP 1
   A = 172
   PSET (T, A)
   NEXT T
   FOR T = 52 TO 599 STEP 1
   A = 173
   PSET (T, A)
   NEXT T
   FOR T = 52 TO 599 STEP 1
   A = 174
   PSET (T, A)
   NEXT T
   FOR T = 52 TO 599 STEP 1
   A = 175
   PSET (T, A)
   NEXT T
   FOR T = 52 TO 599 STEP 1
   A = 176
   PSET (T, A)
   NEXT T
   FOR T = 52 TO 599 STEP 1
   A = 177
   PSET (T, A)
   NEXT T
   FOR T = 52 TO 599 STEP 1
   A = 178
   PSET (T, A)
   NEXT T
   FOR T = 52 TO 599 STEP 1
   A = 179
   PSET (T, A)
   NEXT T
   FOR T = 52 TO 599 STEP 1
   A = 180
   PSET (T, A)
   NEXT T
   FOR T = 52 TO 599 STEP 1
   A = 181
   PSET (T, A)
   NEXT T
   FOR T = 52 TO 599 STEP 1
   A = 182
   PSET (T, A)
   NEXT T
   FOR T = 52 TO 599 STEP 1
   A = 183
   PSET (T, A)
   NEXT T
   FOR T = 52 TO 599 STEP 1
   A = 184
   PSET (T, A)
   NEXT T
   FOR T = 52 TO 599 STEP 1
   A = 185
   PSET (T, A)
   NEXT T
   FOR T = 52 TO 599 STEP 1
   A = 186
   PSET (T, A)
   NEXT T
   FOR T = 52 TO 599 STEP 1
   A = 187
   PSET (T, A)
   NEXT T
   FOR T = 52 TO 599 STEP 1
   A = 188
   PSET (T, A)
   NEXT T
   FOR T = 52 TO 599 STEP 1
   A = 189
   PSET (T, A)
   NEXT T
   FOR T = 52 TO 599 STEP 1
   A = 190
   PSET (T, A)
   NEXT T
   FOR T = 52 TO 599 STEP 1
   A = 191
   PSET (T, A)
   NEXT T
   FOR T = 52 TO 599 STEP 1
   A = 192
   PSET (T, A)
   NEXT T
   FOR T = 52 TO 599 STEP 1
   A = 193
   PSET (T, A)
   NEXT T
   FOR T = 52 TO 599 STEP 1
   A = 194
   PSET (T, A)
   NEXT T
   FOR T = 52 TO 599 STEP 1
   A = 195
   PSET (T, A)
   NEXT T
   FOR T = 52 TO 599 STEP 1
   A = 196
   PSET (T, A)
   NEXT T
   FOR T = 52 TO 599 STEP 1
   A = 197
   PSET (T, A)
   NEXT T
   FOR T = 52 TO 599 STEP 1
   A = 198
   PSET (T, A)
   NEXT T
   FOR T = 52 TO 599 STEP 1
   A = 199
   PSET (T, A)
   NEXT T
   COLOR 2
   FOR T = 52 TO 599 STEP 2
   A = 200
   PSET (T, A)
   NEXT T
   FOR T = 52 TO 599 STEP 2
   A = 201
   PSET (T, A)
   NEXT T
   FOR T = 52 TO 599 STEP 2
   A = 202
   PSET (T, A)
   NEXT T
   FOR T = 52 TO 599 STEP 2
   A = 202
   PSET (T, A)
   NEXT T
   FOR T = 52 TO 599 STEP 2
   A = 203
   PSET (T, A)
   NEXT T
   FOR T = 52 TO 599 STEP 2
   A = 204
   PSET (T, A)
   NEXT T
   FOR T = 52 TO 599 STEP 2
   A = 205
   PSET (T, A)
   NEXT T
   FOR T = 52 TO 599 STEP 2
   A = 206
   PSET (T, A)
   NEXT T
   FOR T = 52 TO 599 STEP 2
   A = 207
   PSET (T, A)
   NEXT T
   FOR T = 52 TO 599 STEP 2
   A = 208
   PSET (T, A)
   NEXT T
   FOR T = 52 TO 599 STEP 2
   A = 209
   PSET (T, A)
   NEXT T
   FOR T = 52 TO 599 STEP 2
   A = 210
   PSET (T, A)
   NEXT T
   FOR T = 52 TO 599 STEP 2
   A = 211
   PSET (T, A)
   NEXT T
   FOR T = 52 TO 599 STEP 2
   A = 212
   PSET (T, A)
   NEXT T
   FOR T = 52 TO 599 STEP 2
   A = 213
   PSET (T, A)
   NEXT T
   FOR T = 52 TO 599 STEP 2
   A = 214
   PSET (T, A)
   NEXT T
   FOR T = 52 TO 599 STEP 2
   A = 215
   PSET (T, A)
   NEXT T
   FOR T = 52 TO 599 STEP 2
   A = 216
   PSET (T, A)
   NEXT T
   FOR T = 52 TO 599 STEP 2
   A = 217
   PSET (T, A)
   NEXT T
   FOR T = 52 TO 599 STEP 2
   A = 218
   PSET (T, A)
   NEXT T
   FOR T = 52 TO 599 STEP 2
   A = 219
   PSET (T, A)
   NEXT T
   FOR T = 52 TO 599 STEP 2
   A = 220
   PSET (T, A)
   NEXT T
   FOR T = 52 TO 599 STEP 2
   A = 221
   PSET (T, A)
   NEXT T
   FOR T = 52 TO 599 STEP 2
   A = 222
   PSET (T, A)
   NEXT T
   FOR T = 52 TO 599 STEP 2
   A = 223
   PSET (T, A)
   NEXT T
   FOR T = 52 TO 599 STEP 2
   A = 224
   PSET (T, A)
   NEXT T
   FOR T = 52 TO 599 STEP 2
   A = 225
   PSET (T, A)
   NEXT T
   FOR T = 52 TO 599 STEP 2
   A = 226
   PSET (T, A)
   NEXT T
   FOR T = 52 TO 599 STEP 2
   A = 227
   PSET (T, A)
   NEXT T
   FOR T = 52 TO 599 STEP 2
   A = 228
   PSET (T, A)
   NEXT T
   FOR T = 52 TO 599 STEP 2
   A = 229
   PSET (T, A)
   NEXT T
   FOR T = 52 TO 599 STEP 2
   A = 230
   PSET (T, A)
   NEXT T
   FOR T = 52 TO 599 STEP 2
   A = 231
   PSET (T, A)
   NEXT T
   FOR T = 52 TO 599 STEP 2
   A = 232
   PSET (T, A)
   NEXT T
   FOR T = 52 TO 599 STEP 2
   A = 233
   PSET (T, A)
   NEXT T
   FOR T = 52 TO 599 STEP 2
   A = 234
   PSET (T, A)
   NEXT T
   FOR T = 52 TO 599 STEP 2
   A = 235
   PSET (T, A)
   NEXT T
   FOR T = 52 TO 599 STEP 2
   A = 236
   PSET (T, A)
   NEXT T
   FOR T = 52 TO 599 STEP 2
   A = 237
   PSET (T, A)
   NEXT T
   FOR T = 52 TO 599 STEP 2
   A = 238
   PSET (T, A)
   NEXT T
   FOR T = 52 TO 599 STEP 2
   A = 239
   PSET (T, A)
   NEXT T
   FOR T = 52 TO 599 STEP 2
   A = 240
   PSET (T, A)
   NEXT T
   FOR T = 52 TO 599 STEP 2
   A = 241
   PSET (T, A)
   NEXT T
   FOR T = 52 TO 599 STEP 2
   A = 242
   PSET (T, A)
   NEXT T
   FOR T = 52 TO 599 STEP 2
   A = 243
   PSET (T, A)
   NEXT T
   FOR T = 52 TO 599 STEP 2
   A = 244
   PSET (T, A)
   NEXT T
   FOR T = 52 TO 599 STEP 2
   A = 245
   PSET (T, A)
   NEXT T
   FOR T = 52 TO 599 STEP 2
   A = 246
   PSET (T, A)
   NEXT T
   FOR T = 52 TO 599 STEP 2
   A = 247
   PSET (T, A)
   NEXT T
   FOR T = 52 TO 599 STEP 2
   A = 248
   PSET (T, A)
   NEXT T
   FOR T = 52 TO 599 STEP 2
   A = 249
   PSET (T, A)
   NEXT T
   FOR T = 52 TO 599 STEP 2
   A = 250
   PSET (T, A)
   NEXT T
   FOR T = 52 TO 599 STEP 2
   A = 251
   PSET (T, A)
   NEXT T
   FOR T = 52 TO 599 STEP 2
   A = 252
   PSET (T, A)
   NEXT T
   FOR T = 52 TO 599 STEP 2
   A = 253
   PSET (T, A)
   NEXT T
   FOR T = 52 TO 599 STEP 2
   A = 254
   PSET (T, A)
   NEXT T
   FOR T = 52 TO 599 STEP 2
   A = 255
   PSET (T, A)
   NEXT T
   FOR T = 52 TO 599 STEP 2
   A = 256
   PSET (T, A)
   NEXT T
   FOR T = 52 TO 599 STEP 2
   A = 257
   PSET (T, A)
   NEXT T
   FOR T = 52 TO 599 STEP 2
   A = 258
   PSET (T, A)
   NEXT T
   FOR T = 52 TO 599 STEP 2
   A = 259
   PSET (T, A)
   NEXT T
   FOR T = 52 TO 599 STEP 2
   A = 260
   PSET (T, A)
   NEXT T
   FOR T = 52 TO 599 STEP 2
   A = 261
   PSET (T, A)
   NEXT T
   FOR T = 52 TO 599 STEP 2
   A = 262
   PSET (T, A)
   NEXT T
   FOR T = 52 TO 599 STEP 2
   A = 263
   PSET (T, A)
   NEXT T
   FOR T = 52 TO 599 STEP 2
   A = 264
   PSET (T, A)
   NEXT T
   FOR T = 52 TO 599 STEP 2
   A = 265
   PSET (T, A)
   NEXT T
   FOR T = 52 TO 599 STEP 2
   A = 266
   PSET (T, A)
   NEXT T
   FOR T = 52 TO 599 STEP 2
   A = 267
   PSET (T, A)
   NEXT T
   FOR T = 52 TO 599 STEP 2
   A = 268
   PSET (T, A)
   NEXT T
   FOR T = 52 TO 599 STEP 2
   A = 269
   PSET (T, A)
   NEXT T
   FOR T = 52 TO 599 STEP 2
   A = 270
   PSET (T, A)
   NEXT T
   FOR T = 52 TO 599 STEP 2
   A = 271
   PSET (T, A)
   NEXT T
   FOR T = 52 TO 599 STEP 2
   A = 272
   PSET (T, A)
   NEXT T
   FOR T = 52 TO 599 STEP 2
   A = 273
   PSET (T, A)
   NEXT T
   FOR T = 52 TO 599 STEP 2
   A = 274
   PSET (T, A)
   NEXT T
   FOR T = 52 TO 599 STEP 2
   A = 275
   PSET (T, A)
   NEXT T
   FOR T = 52 TO 599 STEP 2
   A = 276
   PSET (T, A)
   NEXT T
   FOR T = 52 TO 599 STEP 2
   A = 277
   PSET (T, A)
   NEXT T
   FOR T = 52 TO 599 STEP 2
   A = 278
   PSET (T, A)
   NEXT T
   FOR T = 52 TO 599 STEP 2
   A = 279
   PSET (T, A)
   NEXT T
   FOR T = 52 TO 599 STEP 2
   A = 280
   PSET (T, A)
   NEXT T
   FOR T = 52 TO 599 STEP 2
   A = 281
   PSET (T, A)
   NEXT T
   FOR T = 52 TO 599 STEP 2
   A = 282
   PSET (T, A)
   NEXT T
   FOR T = 52 TO 599 STEP 2
   A = 283
   PSET (T, A)
   NEXT T
   FOR T = 52 TO 599 STEP 2
   A = 284
   PSET (T, A)
   NEXT T
   FOR T = 52 TO 599 STEP 2
   A = 285
   PSET (T, A)
   NEXT T
   FOR T = 52 TO 599 STEP 2
   A = 286
   PSET (T, A)
   NEXT T
   FOR T = 52 TO 599 STEP 2
   A = 287
   PSET (T, A)
   NEXT T
   FOR T = 52 TO 599 STEP 2
   A = 288
   PSET (T, A)
   NEXT T
   FOR T = 52 TO 599 STEP 2
   A = 289
   PSET (T, A)
   NEXT T
   FOR T = 52 TO 599 STEP 2
   A = 290
   PSET (T, A)
   NEXT T
   FOR T = 52 TO 599 STEP 2
   A = 291
   PSET (T, A)
   NEXT T
   FOR T = 52 TO 599 STEP 2
   A = 292
   PSET (T, A)
   NEXT T
   FOR T = 52 TO 599 STEP 2
   A = 293
   PSET (T, A)
   NEXT T
   FOR T = 52 TO 599 STEP 2
   A = 294
   PSET (T, A)
   NEXT T
   FOR T = 52 TO 599 STEP 2
   A = 295
   PSET (T, A)
   NEXT T
   FOR T = 52 TO 599 STEP 2
   A = 296
   PSET (T, A)
   NEXT T
   FOR T = 52 TO 599 STEP 2
   A = 297
   PSET (T, A)
   NEXT T
   FOR T = 52 TO 599 STEP 2
   A = 298
   PSET (T, A)
   NEXT T
   FOR T = 52 TO 599 STEP 2
   A = 299
   PSET (T, A)
   NEXT T
   FOR T = 52 TO 599 STEP 2
   A = 300
   PSET (T, A)
   NEXT T
   FOR T = 52 TO 599 STEP 2
   A = 301
   PSET (T, A)
   NEXT T
   FOR T = 52 TO 599 STEP 2
   A = 302
   PSET (T, A)
   NEXT T
   FOR T = 52 TO 599 STEP 2
   A = 303
   PSET (T, A)
   NEXT T
   FOR T = 52 TO 599 STEP 2
   A = 304
   PSET (T, A)
   NEXT T
   FOR T = 52 TO 599 STEP 2
   A = 305
   PSET (T, A)
   NEXT T
   FOR T = 52 TO 599 STEP 2
   A = 306
   PSET (T, A)
   NEXT T
   FOR T = 52 TO 599 STEP 2
   A = 307
   PSET (T, A)
   NEXT T
   FOR T = 52 TO 599 STEP 2
   A = 308
   PSET (T, A)
   NEXT T
   FOR T = 52 TO 599 STEP 2
   A = 309
   PSET (T, A)
   NEXT T
   FOR T = 52 TO 599 STEP 2
   A = 310
   PSET (T, A)
   NEXT T
   FOR T = 52 TO 599 STEP 2
   A = 311
   PSET (T, A)
   NEXT T
   COLOR 9
   LINE (100, 101)-(470, 101), 1
   LINE (100, 102)-(470, 102), 1
   LINE (100, 103)-(470, 103), 1
   LINE (100, 104)-(470, 104), 1
   LINE (100, 105)-(470, 105), 1
   LINE (100, 106)-(470, 106), 1
   LINE (100, 107)-(470, 107), 1
   LINE (100, 108)-(470, 108), 1
   LINE (100, 109)-(470, 109), 1
   LINE (100, 110)-(470, 110), 1
   LINE (100, 111)-(470, 111), 1
   LINE (100, 112)-(470, 112), 1
   LINE (100, 113)-(470, 113), 1
   LINE (100, 114)-(470, 114), 1
   LINE (100, 115)-(130, 115), 1
   LINE (100, 116)-(130, 116), 1
   LINE (100, 117)-(130, 117), 1
   LINE (100, 118)-(130, 118), 1
   LINE (100, 119)-(130, 119), 1
   LINE (100, 120)-(130, 120), 1
   LINE (100, 121)-(130, 121), 1
   LINE (100, 122)-(130, 122), 1
   LINE (100, 123)-(130, 123), 1
   LINE (100, 124)-(130, 124), 1
   LINE (100, 125)-(130, 125), 1
   LINE (100, 126)-(130, 126), 1
   LINE (100, 127)-(130, 127), 1
   LINE (100, 128)-(130, 128), 1
   LINE (100, 129)-(130, 129), 1
   LINE (100, 130)-(130, 130), 1
   LINE (100, 131)-(130, 131), 1
   LINE (100, 132)-(130, 132), 1
   LINE (100, 133)-(130, 133), 1
   LINE (100, 134)-(130, 134), 1
   LINE (100, 135)-(130, 135), 1
   LINE (100, 136)-(130, 136), 1
   LINE (100, 137)-(130, 137), 1
   LINE (100, 138)-(130, 138), 1
   LINE (100, 139)-(130, 139), 1
   LINE (100, 140)-(130, 140), 1
   LINE (100, 141)-(130, 141), 1
   LINE (100, 142)-(130, 142), 1
   LINE (100, 143)-(130, 143), 1
   LINE (100, 144)-(130, 144), 1
   LINE (100, 145)-(130, 145), 1
   LINE (100, 146)-(130, 146), 1
   LINE (100, 147)-(130, 147), 1
   LINE (100, 148)-(130, 148), 1
   LINE (100, 149)-(130, 149), 1
   LINE (100, 150)-(130, 150), 1
   LINE (100, 151)-(130, 151), 1
   LINE (100, 152)-(130, 152), 1
   LINE (100, 153)-(130, 153), 1
   LINE (100, 154)-(130, 154), 1
   LINE (100, 155)-(130, 155), 1
   LINE (100, 156)-(130, 156), 1
   LINE (100, 157)-(130, 157), 1
   LINE (100, 158)-(130, 158), 1
   LINE (100, 159)-(130, 159), 1
   LINE (100, 160)-(130, 160), 1
   LINE (100, 161)-(130, 161), 1
   LINE (100, 162)-(130, 162), 1
   LINE (100, 163)-(130, 163), 1
   LINE (100, 164)-(130, 164), 1
   LINE (100, 165)-(130, 165), 1
   LINE (100, 166)-(130, 166), 1
   LINE (100, 167)-(130, 167), 1
   LINE (100, 168)-(130, 168), 1
   LINE (100, 169)-(130, 169), 1
   LINE (100, 170)-(130, 170), 1
   LINE (100, 171)-(130, 171), 1
   LINE (100, 172)-(130, 172), 1
   LINE (100, 173)-(130, 173), 1
   LINE (100, 174)-(130, 174), 1
   LINE (100, 175)-(130, 175), 1
   LINE (100, 176)-(130, 176), 1
   LINE (100, 177)-(130, 177), 1
   LINE (100, 178)-(130, 178), 1
   LINE (100, 179)-(130, 179), 1
   LINE (100, 180)-(130, 180), 1
   LINE (100, 181)-(130, 181), 1
   LINE (100, 182)-(130, 182), 1
   LINE (100, 183)-(130, 183), 1
   LINE (100, 184)-(130, 184), 1
   LINE (100, 185)-(130, 185), 1
   LINE (100, 186)-(290, 186), 1
   LINE (100, 187)-(290, 187), 1
   LINE (100, 188)-(290, 188), 1
   LINE (100, 189)-(290, 189), 1
   LINE (100, 190)-(290, 190), 1
   LINE (100, 191)-(290, 191), 1
   LINE (100, 192)-(290, 192), 1
   LINE (100, 193)-(290, 193), 1
   LINE (100, 194)-(290, 194), 1
   LINE (100, 195)-(290, 195), 1
   LINE (100, 196)-(290, 196), 1
   LINE (100, 197)-(290, 197), 1
   LINE (100, 198)-(290, 198), 1
   LINE (100, 199)-(290, 199), 1
   LINE (100, 200)-(290, 200), 1
   LINE (150, 140)-(288, 140), 1
   LINE (150, 141)-(288, 141), 1
   LINE (150, 142)-(288, 142), 1
   LINE (150, 143)-(288, 143), 1
   LINE (150, 144)-(288, 144), 1
   LINE (150, 145)-(288, 145), 1
   LINE (150, 146)-(470, 146), 1
   LINE (150, 147)-(470, 147), 1
   LINE (150, 148)-(470, 148), 1
   LINE (150, 149)-(470, 149), 1
   LINE (150, 150)-(470, 150), 1
   LINE (180, 151)-(470, 151), 1
   LINE (180, 152)-(470, 152), 1
   LINE (180, 153)-(470, 153), 1
   LINE (180, 154)-(470, 154), 1
   LINE (180, 155)-(470, 155), 1
   LINE (180, 156)-(470, 156), 1
   LINE (180, 157)-(470, 157), 1
   LINE (180, 158)-(470, 158), 1
   LINE (180, 159)-(470, 159), 1
   LINE (180, 160)-(470, 160), 1
   LINE (180, 161)-(220, 161), 1
   LINE (180, 162)-(220, 162), 1
   LINE (180, 163)-(220, 163), 1
   LINE (180, 164)-(220, 164), 1
   LINE (180, 165)-(220, 165), 1
   LINE (180, 166)-(220, 166), 1
   LINE (180, 167)-(220, 167), 1
   LINE (180, 168)-(220, 168), 1
   LINE (180, 169)-(220, 169), 1
   LINE (180, 170)-(220, 170), 1
   LINE (180, 171)-(220, 171), 1
   LINE (180, 172)-(220, 172), 1
   LINE (180, 173)-(220, 173), 1
   LINE (180, 174)-(220, 174), 1
   LINE (180, 175)-(220, 175), 1
   LINE (180, 176)-(220, 176), 1
   LINE (180, 177)-(220, 177), 1
   LINE (180, 178)-(220, 178), 1
   LINE (180, 179)-(220, 179), 1
   LINE (180, 180)-(220, 180), 1
   LINE (180, 181)-(290, 181), 1
   LINE (180, 182)-(290, 182), 1
   LINE (180, 183)-(290, 183), 1
   LINE (180, 184)-(290, 184), 1
   LINE (180, 185)-(290, 185), 1
   LINE (180, 186)-(290, 186), 1
   LINE (200, 115)-(287, 115), 1
   LINE (200, 116)-(287, 116), 1
   LINE (200, 117)-(287, 117), 1
   LINE (200, 118)-(287, 118), 1
   LINE (200, 119)-(287, 119), 1
   LINE (200, 120)-(287, 120), 1
   LINE (200, 121)-(220, 121), 1
   LINE (200, 122)-(220, 122), 1
   LINE (200, 123)-(220, 123), 1
   LINE (200, 124)-(220, 124), 1
   LINE (200, 125)-(220, 125), 1
   LINE (200, 126)-(220, 126), 1
   LINE (200, 127)-(220, 127), 1
   LINE (200, 128)-(220, 128), 1
   LINE (200, 129)-(220, 129), 1
   LINE (200, 130)-(220, 130), 1
   LINE (200, 131)-(220, 131), 1
   LINE (200, 132)-(220, 132), 1
   LINE (200, 133)-(220, 133), 1
   LINE (200, 134)-(220, 134), 1
   LINE (200, 135)-(220, 135), 1
   LINE (200, 136)-(220, 136), 1
   LINE (200, 137)-(220, 137), 1
   LINE (200, 138)-(220, 138), 1
   LINE (200, 139)-(220, 139), 1
   LINE (271, 140)-(287, 140), 1
   LINE (271, 141)-(287, 141), 1
   LINE (271, 142)-(287, 142), 1
   LINE (271, 143)-(287, 143), 1
   LINE (271, 144)-(287, 144), 1
   LINE (271, 145)-(287, 145), 1
   LINE (271, 146)-(287, 146), 1
   LINE (271, 147)-(287, 147), 1
   LINE (271, 148)-(287, 148), 1
   LINE (271, 149)-(287, 149), 1
   LINE (271, 150)-(287, 150), 1
   LINE (271, 151)-(287, 151), 1
   LINE (271, 152)-(287, 152), 1
   LINE (271, 153)-(287, 153), 1
   LINE (271, 154)-(287, 154), 1
   LINE (271, 155)-(287, 155), 1
   LINE (271, 156)-(287, 156), 1
   LINE (271, 157)-(287, 157), 1
   LINE (271, 158)-(287, 158), 1
   LINE (271, 159)-(287, 159), 1
   LINE (271, 160)-(287, 160), 1
   LINE (271, 161)-(289, 161), 1
   LINE (271, 162)-(289, 162), 1
   LINE (271, 163)-(289, 163), 1
   LINE (271, 164)-(289, 164), 1
   LINE (271, 165)-(289, 165), 1
   LINE (271, 166)-(289, 166), 1
   LINE (271, 167)-(289, 167), 1
   LINE (271, 168)-(289, 168), 1
   LINE (271, 169)-(289, 169), 1
   LINE (271, 170)-(289, 170), 1
   LINE (271, 171)-(289, 171), 1
   LINE (271, 172)-(289, 172), 1
   LINE (271, 173)-(289, 173), 1
   LINE (271, 174)-(289, 174), 1
   LINE (271, 175)-(289, 175), 1
   LINE (271, 176)-(289, 176), 1
   LINE (271, 177)-(289, 177), 1
   LINE (271, 178)-(289, 178), 1
   LINE (271, 179)-(289, 179), 1
   LINE (271, 180)-(289, 180), 1
   LINE (271, 181)-(289, 181), 1
   LINE (271, 182)-(289, 182), 1
   LINE (271, 183)-(289, 183), 1
   LINE (271, 184)-(289, 184), 1
   LINE (271, 185)-(289, 185), 1
   LINE (271, 186)-(289, 186), 1
   LINE (271, 115)-(287, 115), 1
   LINE (271, 116)-(287, 116), 1
   LINE (271, 117)-(287, 117), 1
   LINE (271, 118)-(287, 118), 1
   LINE (271, 119)-(287, 119), 1
   LINE (271, 120)-(287, 120), 1
   LINE (271, 121)-(287, 121), 1
   LINE (271, 122)-(287, 122), 1
   LINE (271, 123)-(287, 123), 1
   LINE (271, 124)-(287, 124), 1
   LINE (271, 125)-(287, 125), 1
   LINE (271, 126)-(287, 126), 1
   LINE (271, 127)-(287, 127), 1
   LINE (271, 128)-(287, 128), 1
   LINE (271, 129)-(287, 129), 1
   LINE (271, 130)-(287, 130), 1
   LINE (271, 131)-(287, 131), 1
   LINE (271, 132)-(287, 132), 1
   LINE (271, 133)-(287, 133), 1
   LINE (271, 134)-(287, 134), 1
   LINE (271, 135)-(287, 135), 1
   LINE (271, 136)-(287, 136), 1
   LINE (271, 137)-(287, 137), 1
   LINE (271, 138)-(287, 138), 1
   LINE (271, 139)-(287, 139), 1
   LINE (313, 161)-(334, 161), 1
   LINE (314, 162)-(335, 162), 1
   LINE (315, 163)-(336, 163), 1
   LINE (316, 164)-(337, 164), 1
   LINE (317, 165)-(338, 165), 1
   LINE (318, 166)-(339, 166), 1
   LINE (319, 167)-(340, 167), 1
   LINE (320, 168)-(341, 168), 1
   LINE (321, 169)-(342, 169), 1
   LINE (322, 170)-(343, 170), 1
   LINE (323, 171)-(344, 171), 1
   LINE (324, 172)-(345, 172), 1
   LINE (325, 173)-(346, 173), 1
   LINE (326, 174)-(347, 174), 1
   LINE (327, 175)-(348, 175), 1
   LINE (328, 176)-(349, 176), 1
   LINE (329, 177)-(350, 177), 1
   LINE (330, 178)-(351, 178), 1
   LINE (331, 179)-(352, 179), 1
   LINE (332, 180)-(353, 180), 1
   LINE (333, 181)-(354, 181), 1
   LINE (334, 182)-(355, 182), 1
   LINE (335, 183)-(356, 183), 1
   LINE (336, 184)-(357, 184), 1
   LINE (337, 185)-(358, 185), 1
   LINE (338, 186)-(359, 186), 1
   LINE (339, 187)-(360, 187), 1
   LINE (340, 188)-(361, 188), 1
   LINE (341, 189)-(362, 189), 1
   LINE (342, 190)-(363, 190), 1
   LINE (343, 191)-(364, 191), 1
   LINE (344, 192)-(365, 192), 1
   LINE (345, 193)-(366, 193), 1
   LINE (346, 194)-(367, 194), 1
   LINE (347, 195)-(368, 195), 1
   LINE (348, 196)-(369, 196), 1
   LINE (349, 197)-(370, 197), 1
   LINE (350, 198)-(371, 198), 1
   LINE (351, 199)-(372, 199), 1
   LINE (352, 200)-(373, 200), 1
   LINE (354, 115)-(389, 115), 1
   LINE (354, 116)-(389, 116), 1
   LINE (354, 117)-(389, 117), 1
   LINE (354, 118)-(389, 118), 1
   LINE (354, 119)-(389, 119), 1
   LINE (354, 120)-(389, 120), 1
   LINE (354, 121)-(389, 121), 1
   LINE (354, 122)-(389, 122), 1
   LINE (354, 123)-(389, 123), 1
   LINE (354, 124)-(389, 124), 1
   LINE (354, 125)-(389, 125), 1
   LINE (354, 126)-(389, 126), 1
   LINE (354, 127)-(389, 127), 1
   LINE (354, 128)-(389, 128), 1
   LINE (354, 129)-(389, 129), 1
   LINE (354, 130)-(389, 130), 1
   LINE (354, 131)-(389, 131), 1
   LINE (354, 132)-(389, 132), 1
   LINE (354, 133)-(389, 133), 1
   LINE (354, 134)-(389, 134), 1
   LINE (354, 135)-(389, 135), 1
   LINE (354, 136)-(389, 136), 1
   LINE (354, 137)-(389, 137), 1
   LINE (354, 138)-(389, 138), 1
   LINE (354, 139)-(389, 139), 1
   LINE (354, 140)-(389, 140), 1
   LINE (354, 141)-(389, 141), 1
   LINE (354, 142)-(389, 142), 1
   LINE (354, 143)-(389, 143), 1
   LINE (354, 144)-(389, 144), 1
   LINE (354, 145)-(389, 145), 1
   LINE (354, 146)-(389, 146), 1
   LINE (354, 147)-(389, 147), 1
   LINE (354, 148)-(389, 148), 1
   LINE (354, 149)-(389, 149), 1
   LINE (354, 150)-(389, 150), 1
   LINE (354, 151)-(389, 151), 1
   LINE (354, 152)-(389, 152), 1
   LINE (354, 153)-(389, 153), 1
   LINE (354, 154)-(389, 154), 1
   LINE (354, 155)-(389, 155), 1
   LINE (354, 156)-(389, 156), 1
   LINE (354, 157)-(389, 157), 1
   LINE (354, 158)-(389, 158), 1
   LINE (354, 159)-(389, 159), 1
   LINE (354, 160)-(389, 160), 1
   LINE (371, 161)-(391, 161), 1
   LINE (371, 162)-(391, 162), 1
   LINE (371, 163)-(391, 163), 1
   LINE (371, 164)-(391, 164), 1
   LINE (371, 165)-(391, 165), 1
   LINE (371, 166)-(391, 166), 1
   LINE (371, 167)-(391, 167), 1
   LINE (371, 168)-(391, 168), 1
   LINE (371, 169)-(391, 169), 1
   LINE (371, 170)-(391, 170), 1
   LINE (371, 171)-(391, 171), 1
   LINE (371, 172)-(391, 172), 1
   LINE (371, 173)-(391, 173), 1
   LINE (371, 174)-(391, 174), 1
   LINE (371, 175)-(391, 175), 1
   LINE (371, 176)-(391, 176), 1
   LINE (371, 177)-(391, 177), 1
   LINE (371, 178)-(391, 178), 1
   LINE (371, 179)-(391, 179), 1
   LINE (371, 180)-(391, 180), 1
   LINE (371, 181)-(391, 181), 1
   LINE (371, 182)-(391, 182), 1
   LINE (371, 183)-(391, 183), 1
   LINE (371, 184)-(391, 184), 1
   LINE (371, 185)-(391, 185), 1
   LINE (371, 186)-(391, 186), 1
   LINE (371, 187)-(391, 187), 1
   LINE (371, 188)-(391, 188), 1
   LINE (371, 189)-(391, 189), 1
   LINE (371, 190)-(391, 190), 1
   LINE (371, 191)-(391, 191), 1
   LINE (371, 192)-(391, 192), 1
   LINE (371, 193)-(391, 193), 1
   LINE (371, 194)-(391, 194), 1
   LINE (371, 195)-(391, 195), 1
   LINE (371, 196)-(391, 196), 1
   LINE (371, 197)-(391, 197), 1
   LINE (371, 198)-(391, 198), 1
   LINE (371, 199)-(391, 199), 1
   LINE (371, 200)-(391, 200), 1
   LINE (431, 114)-(470, 114), 1
   LINE (431, 115)-(470, 115), 1
   LINE (431, 116)-(470, 116), 1
   LINE (431, 117)-(470, 117), 1
   LINE (431, 118)-(470, 118), 1
   LINE (431, 119)-(470, 119), 1
   LINE (431, 120)-(470, 120), 1
   LINE (431, 121)-(470, 121), 1
   LINE (431, 122)-(470, 122), 1
   LINE (431, 123)-(470, 123), 1
   LINE (431, 124)-(470, 124), 1
   LINE (431, 125)-(470, 125), 1
   LINE (431, 126)-(470, 126), 1
   LINE (431, 127)-(470, 127), 1
   LINE (431, 128)-(470, 128), 1
   LINE (431, 129)-(470, 129), 1
   LINE (431, 130)-(470, 130), 1
   LINE (431, 131)-(470, 131), 1
   LINE (431, 132)-(470, 132), 1
   LINE (431, 133)-(470, 133), 1
   LINE (431, 134)-(470, 134), 1
   LINE (431, 135)-(470, 135), 1
   LINE (431, 136)-(470, 136), 1
   LINE (431, 137)-(470, 137), 1
   LINE (431, 138)-(470, 138), 1
   LINE (431, 139)-(470, 139), 1
   LINE (431, 140)-(470, 140), 1
   LINE (431, 141)-(470, 141), 1
   LINE (431, 142)-(470, 142), 1
   LINE (431, 143)-(470, 143), 1
   LINE (431, 144)-(470, 144), 1
   LINE (431, 145)-(470, 145), 1
   LINE (431, 146)-(470, 146), 1
   LINE (431, 147)-(470, 147), 1
   LINE (431, 148)-(470, 148), 1
   LINE (431, 149)-(470, 149), 1
   LINE (431, 150)-(470, 150), 1
   LINE (431, 151)-(470, 151), 1
   LINE (431, 152)-(470, 152), 1
   LINE (431, 153)-(470, 153), 1
   LINE (431, 154)-(470, 154), 1
   LINE (431, 155)-(470, 155), 1
   LINE (431, 156)-(470, 156), 1
   LINE (431, 157)-(470, 157), 1
   LINE (431, 158)-(470, 158), 1
   LINE (431, 159)-(470, 169), 1
   LINE (431, 160)-(470, 160), 1
   LINE (431, 161)-(470, 161), 1
   LINE (431, 162)-(470, 162), 1
   LINE (431, 163)-(470, 163), 1
   LINE (431, 164)-(470, 164), 1
   LINE (431, 165)-(470, 165), 1
   LINE (431, 166)-(470, 166), 1
   LINE (431, 167)-(470, 167), 1
   LINE (431, 168)-(470, 168), 1
   LINE (431, 169)-(470, 169), 1
   LINE (431, 170)-(470, 170), 1
   LINE (431, 171)-(470, 171), 1
   LINE (431, 172)-(470, 172), 1
   LINE (431, 173)-(470, 173), 1
   LINE (431, 174)-(470, 174), 1
   LINE (431, 175)-(470, 175), 1
   LINE (431, 176)-(470, 176), 1
   LINE (431, 177)-(470, 177), 1
   LINE (431, 178)-(470, 178), 1
   LINE (431, 179)-(470, 179), 1
   LINE (431, 180)-(470, 180), 1
   LINE (431, 181)-(530, 181), 1
   LINE (431, 182)-(530, 182), 1
   LINE (431, 183)-(530, 183), 1
   LINE (431, 184)-(530, 184), 1
   LINE (431, 185)-(530, 185), 1
   LINE (431, 186)-(530, 186), 1
   LINE (431, 187)-(530, 187), 1
   LINE (431, 188)-(530, 188), 1
   LINE (431, 189)-(530, 189), 1
   LINE (431, 190)-(530, 190), 1
   LINE (431, 191)-(530, 191), 1
   LINE (431, 192)-(530, 192), 1
   LINE (431, 193)-(530, 193), 1
   LINE (431, 194)-(530, 194), 1
   LINE (431, 195)-(530, 195), 1
   LINE (431, 196)-(530, 196), 1
   LINE (431, 197)-(530, 197), 1
   LINE (431, 198)-(530, 198), 1
   LINE (431, 199)-(530, 199), 1
   LINE (431, 200)-(530, 200), 1
   COLOR 15
   PSET (100, 100): DRAW "D100;R100;U60;L50;D10;R30;D35;L50;U70;R70;U15;L100;D20"
   PSET (200, 100): DRAW "D100;R70;U20;L50;U20;R50;U20;L50;U20;R50;U20;L70"
   PSET (270, 100): DRAW "D100;R20;U40;R20;F40;R20;U2;H38;R37;U60;L100"
   PSET (288, 115): DRAW "D30;R65;U30;L65"
   PSET (370, 100): DRAW "D100;R20;U40;R40;D40;R20;U100;L80"
   PSET (390, 115): DRAW "D30;R40;U30;L40"
   PSET (450, 100): DRAW "D100;R80;U20;L60;U80;L20"
   COLOR 1
   LOCATE 8, 62: PRINT "VERSÇO 2.0"
   dt = 5
    tmax = 650
    FOR T = 0 TO tmax STEP dt
    A = 1
    CIRCLE (T, A), (50), 4
    CIRCLE (A, T), (50), 1
    A = 650
    CIRCLE (A, T), (50), 1
    A = 350
    CIRCLE (T, A), (50), 4
    NEXT
    FOR i% = 440 TO 1000 STEP 51
    SOUND i%, i% / 1000
    NEXT i%
    COLOR 8
    Center 19, "PASSWORD "
    LOCATE 19, 45: INPUT ; A$
    A$ = UCASE$(A$)
    IF A$ = "A" THEN GOTO 242
    GOTO 248
242 FOR i% = 440 TO 1000 STEP 51
    SOUND i%, i% / 1000
    NEXT i%
    GOTO 280
248 escala$ = "CDEFAFDAFBCDCDFGAB"
    PLAY "L16"
    FOR i% = 0 TO 6
    PLAY "O" + STR$(i%)
    PLAY "X" + VARPTR$(escala$)
    NEXT i%
    CHAIN "MEMBRO18.BAS"
280 CHAIN "CORPO.BAS"

'Center:
'  Centers text on given row
SUB Center (row, text$)
    LOCATE row, 41 - LEN(text$) / 2
    PRINT text$;
END SUB

