    CLS
    PLAY "t120o1l16b9n0baan0bn0bn0baaan0b9n0baan0b"

    PLAY "o2l16e-9n0e-d-d-n0e-n0e-n0e-d-d-d-n0e-9n0e-d-d-n0e-"

    PLAY "o2l16g-9n0g-een0g-n0g-n0g-eeen0g-9n0g-een0g-"

    PLAY "o2l16b9n0baan0g-n0g-n0g-eeen0o1b9n0baan0b"

      PLAY "T160O0L32EFGEFDC"
      PLAY "T160O0L32EFGEFDC"
      PLAY "T160O0L32EFGEFDC"
      PLAY "T160O0L32EFGEFDC"
      PLAY "T160O0L32EFGEFDC"
      PLAY "T160O0L32EFGEFDC"
      PLAY "T160O0L32EFGEFDC"
      PLAY "T160O0L32EFGEFDC"

